#!/usr/bin/env python3

import sys
import os

if __name__=='__main__':
	if len(sys.argv) == 1:
		print("Missing arguments")
		print("Usage:")
		print(f"stamina MODEL_FILE PROPERTIES_FILE --sstamina(-s)/--pstamina(-p) [OPTIONS]")
		print(f"\nTo see help or usage for STAMINA/STORM or STAMINA/PRISM, please pass in either the -s or -p tags respectively\n")
		sys.exit(1)
	if "-s" in sys.argv or "--sstamina" in sys.argv:
		sys.argv.remove(a for a in ["-s", "--sstamina"])
		args = ""
		for arg in sys.argv:
			args += str(arg) + " "
		sys.exit(os.system(f"sstamina {args}"))
	if "-p" in sys.argv or "--pstamina" in sys.argv:
		sys.argv.remove(a for a in ["-p", "--pstamina"])
		args = ""
		for arg in sys.argv:
			args += str(arg) + " "
		sys.exit(os.system(f"pstamina {args}"))
	if "-h" in sys.argv or "--help" in sys.argv:
		# Print a help message and exit
		print("Usage:")
		print(f"stamina MODEL_FILE PROPERTIES_FILE --sstamina(-s)/--pstamina(-p) [OPTIONS]")
		print(f"\nTo see help or usage for STAMINA/STORM or STAMINA/PRISM, please pass in either the -s or -p tags respectively\n")
		print("Options:")
		print("\t--help (-h):         Shows this message and exits")
		print("\t--sstamina (-s):     Use STAMINA/STORM with the arguments passed in")
		print("\t--pstamina (-p):     Use STAMINA/PRISM with the arguments passed in")

